# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_igw38RRf6CVrgmA4Zsjgz9SDWLhz5Kk
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(-2 * np.pi, 2 * np.pi, 1000)
y = np.sin(x)
plt.figure(figsize=(10, 6))
plt.plot(x, y, label='sin(x)', color='blue')
plt.title('Sinus funksiya grafigi')
plt.xlabel('X (rad)')
plt.ylabel('Y (sin(x))')
plt.axhline(0, color='black', lw=0.5, ls='--')
plt.axvline(0, color='black', lw=0.5, ls='--')
plt.grid()
plt.legend()
plt.xlim([-2 * np.pi, 2 * np.pi])
plt.ylim([-1.5, 1.5])
plt.show()